### ISSUE TITLE
[Bug] Kitsu Watched Indicator

### ISSUE THREAD

**Issue by Demonseeed** [Wilson-Magic/plugin.video.hummingbird#11]
Hello Wilson! First, thank you so much for this addon! I really like what you have created. 

The issue I am running in to is it doesn’t seem that my shows from my “Currently Watching” section of Kitsu seem to have display and indicator of which episodes I have seen, making it impossible to distinguish which episodes I have already seen. 
![image](https://user-images.githubusercontent.com/29167580/78107753-ead9d380-73aa-11ea-810b-ae5e16d08c54.jpg)

In this screenshot, according to the Kitsu app, I have seen up to episode 16. However per the screenshot, there is no indicator. 

Thank you!!

**Comment by Wilson-Magic** [comment]
This is something that will be a part of an update that will come out soon. That will change a bunch about the accounts and fix a bunch of bugs.

To be honest the whole account section with MAL Kitsu and Anilist is pretty terrible at the moment haha.

**Comment by Demonseeed** [comment]
Sounds good, thank you for that!!

While I got you, I really want to express my appreciation for adding fanart.tv integration. Terrible anime artwork has been one of my major pain points in all prior anime addons and you solved that. Thanks again!

**Comment by Wilson-Magic** [comment]
This update that adds this has been released.
