### ISSUE TITLE
Icons I made for Humming Bird

### ISSUE THREAD

**Issue by icpryde** [Wilson-Magic/plugin.video.hummingbird#13]
Hey I wanted to help contribute so I made a new logo for you plus icons for all the categories I hope you enjoy!

I made a set with a background and a set without the background and the idea was to make it look like the Kitsu layout/colours. 

Heres the link: 

https://www.dropbox.com/s/8q3z5f5xp5610ng/icons.zip?dl=0

**Comment by Demonseeed** [comment]
+1, these icons looks great!

+2 if you made icons for each genre 👌

**Comment by icpryde** [comment]
@Demonseeed Looks at the genre section "fuuuuuuuuuuuuuuuuuuuuu that LOL" besides those just make more sense to just use the 1 icon for all of them cause thats insane amount of icons at that point.

**Comment by Demonseeed** [comment]
Yes, yes it is an insane amount of work lmao! It never hurts to ask tho amirite 😂 either way, great job on what you have done, hopefully Wilson will approve too!

**Comment by Wilson-Magic** [comment]
@Demonseeed I do, next update.

**Comment by Wilson-Magic** [comment]
The update that adds these icons has been released. Thanks for these.
