### ISSUE TITLE
[Enhancement] A Search History for the hub configuration.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Wilson-Magic/plugin.video.hummingbird#17]
Hey there, sorry for bothering you on this issue but I think there should be a Search History so that people can look at what they searched in which makes it easier for the person to find their anime. Other video addons like WSbeta or Watchnixtoons have a search history in which use that search history target field for my build to add to my search bar. If you could add a search history that would be great. You made the most amazing addon for anime and I support you on this project, Thank you for everything man.

**Comment by Wilson-Magic** [comment]
I will make a search history soon, thanks for the suggestion.

**Comment by tripod** [comment]
If you are using a Skin like Arctic Zephyr 2/Arctic Horizon you can use this and add it to custom search lists
`ActivateWindow(Videos,”plugin://plugin.video.hummingbird/?action=title_search&page=1&title=$INFO[Skin.String(CustomSearchTerm)]”,return)`

**Comment by Goldenfreddy0703** [comment]
Im actually using the Auramod Skin and i wanted to add this addon to my custom search. The only issue i sadly have on this addon is that i does not produce metadata like the metadata addon. This is a really good addon and i support this addon all the way but if there is a way i can make the wedges not lag for this addon, that would be amazing becouse i love its fanart and its artwork and it titles artwork but when i import the catagories like popular or trending or High Rating as poster veiw, it lags the skin and thats the only sad part i have.

**Comment by tripod** [comment]
I use Arctic Horizon, it works flawlessly for all info. for myself personally, do you mean info like this?

![screenshot000](https://user-images.githubusercontent.com/568488/79517237-f3135d80-8090-11ea-8858-9927fc133da8.png)

![screenshot002](https://user-images.githubusercontent.com/568488/79517244-f9093e80-8090-11ea-84e1-763cc8a354ea.png)

![screenshot003](https://user-images.githubusercontent.com/568488/79517252-feff1f80-8090-11ea-941a-77fcc3893b00.png)

**Comment by Goldenfreddy0703** [comment]
The main reason why i still use aruamod is becouse it has a netflix feel into it and the titles of every movie or tv show had artwork on it and i like that personly, I use to use the skin Titan Bingie but it was not as good as aura and when i tried aura for the fist time, it was probably the best multiface interface i ever seen and everything works amazing on there and i cant wait to add live tv to it, I also love the trakt manager with the seren addon which adds alot of great media and especially TheMovieDB Helper.

**Comment by tripod** [comment]
Fair enoug :D
