### ISSUE TITLE
Lag for series with many episodes

### ISSUE THREAD

**Issue by TaiDak** [Wilson-Magic/plugin.video.hummingbird#6]
Hi, series like one piece and cased closed lag a lot when loading, so I wanted to ask wether you could implement some sort of divisions for series like those, series that have a large amount of episodes. 
doko-desuka has something like that in his WSbeta that divides one piece by 100 episodes, and it loads pretty fast, although his add-on is pretty barebones. I understand of course if you're limited
 in resources or its impractical/hard to accomplish.

**Comment by Wilson-Magic** [comment]
How long is it taking you? It has been a max of maybe 5-10 seconds for episodes. And that caches the calls so it should only be a second or so for the next day. It would be a hassle to split it. The reason it takes a while for shows like that is that it has to do 30+ requests to get the episode data for One Piece. Not really much I can do to speed that up. However, I think getting all the episodes on one page is more important and looks nicer.

Lol tbh you should have seen how long it used to take. I remember it taking 25+ seconds to get one piece's episodes haha.

**Comment by TaiDak** [comment]
It takes about 10 to 15 for me. I was thinking it could be similiar to wsbeta, in which he splits them by 100, sort of like seasons, not pages. having it split in pages would be far more annoying than having to wait.

**Comment by TaiDak** [comment]
Sorry my apologies, it doesn't take 10-15 seconds for me, one piece takes at least one full minute to load, though that might be due to the limitations of the firestick
