### ISSUE TITLE
[Bug] Kitsu not showing my lists properly

### ISSUE THREAD

**Issue by icpryde** [Wilson-Magic/plugin.video.hummingbird#7]
So I found an interesting issue, when I log into my kitsu account and check the lists like "currently watching" or any other list for that matter it lists random anime that are not actually on my lists at all and it does not list any anime that I have on my list?

Example "currently watching" on the Kitsu site shows my real list like this:

![001](https://user-images.githubusercontent.com/29389746/78031387-7b73cd80-7331-11ea-9cee-7e15c62a0bed.PNG)

Then when I go to Kitsu from Kodi using hummingbird it shows this random list:

![002](https://user-images.githubusercontent.com/29389746/78031424-89c1e980-7331-11ea-9442-306042df0422.PNG)

Any idea why this happens? also heres my log file in case that helps.

http://paste.ubuntu.com/p/yNbSnffSM5/

**Comment by DaisyF8** [comment]
Me too, or actually my girlfriend.

My account works okay. But when I switch accounts all lists are empty except finished, and that has all sorts of anime she never even looked at ???

**Comment by Wilson-Magic** [comment]
Sorry about this. i made an error in the log in system that made this happen. It is fixed in 0.5.0, which is the update I just released. @DaisyF8 Can you try again with your girlfriends account. It should be fixed now!
